words = ["APPLE", "BANANA", "ORANGE", "GIRAFFE", "ELEPHANT", "PYTHON", "PROGRAMMING", "COMPUTER", "INTERNET",
         "DATABASE", "ALGORITHM", "LIBRARY", "KEYBOARD", "MONITOR", "HEADPHONES", "CHAIR", "TABLE", "LAPTOP",
         "NOTEBOOK", "PENGUIN", "ZEBRA", "CACTUS", "MOUNTAIN", "OCEAN", "RAINBOW", "SUNSHINE", "FLOWER", "STAR",
         "GALAXY", "UNIVERSE", "ROBOT", "SPACE", "ROCKET", "ASTRONAUT", "CHOCOLATE", "COFFEE", "TELESCOPE",
         "MICROPHONE", "BICYCLE", "ADVENTURE", "JOURNEY", "DESTINATION", "EXPLORER", "DISCOVERY", "WONDER",
         "HARMONY", "SYMPHONY", "MELODY"]